name: shopping_repository_interface
description: "A new Flutter package project."
version: 3.0.0
homepage: https://github.com/Iconica-Development/flutter_shopping/packages/shopping_repository_interface
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
