name: flutter_shopping_local
description: "A local Flutter module for a shopping."
version: 2.0.0
repository: https://github.com/Iconica-Development/flutter_shopping

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shopping_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0
