name: amazon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.1.1
  go_router: 12.1.3
  flutter_nested_categories:
    git:
      url: https://github.com/Iconica-Development/flutter_nested_categories
      ref: 0.0.1
  flutter_product_page:
    path: ../../flutter_product_page
  flutter_shopping_cart:
    path: ../../flutter_shopping_cart
  flutter_order_details:
    path: ../../flutter_order_details
  flutter_shopping:
    path: ../../flutter_shopping

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
