name: firebase_shopping_repository
description: "A new Flutter package project."
version: 3.0.0
homepage: https://github.com/Iconica-Development/flutter_shopping/packages/firebase_shopping_repository
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  rxdart: ^0.28.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  shopping_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
