name: flutter_product_page
description: "A Flutter module for the product page"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  skeletonizer: ^1.1.1
  cached_network_image: ^3.3.1
  flutter_nested_categories:
    git:
      url: https://github.com/Iconica-Development/flutter_nested_categories
      ref: 0.0.1
  flutter_shopping:
    git:
      url: https://github.com/Iconica-Development/flutter_shopping
      path: packages/flutter_shopping
      ref: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
  uses-material-design: true
