name: flutter_product_page
description: "A Flutter module for the product page"
version: 2.0.0
repository: https://github.com/Iconica-Development/flutter_shopping

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  skeletonizer: ^1.1.1
  cached_network_image: ^3.3.1
  flutter_nested_categories:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^0.0.1
  flutter_shopping_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^2.0.0
  collection: ^1.18.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: 7.0.0

flutter:
  uses-material-design: true
