name: flutter_product_page
description: "A Flutter module for the product page"
publish_to: 'none'
version: 1.0.0+1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  skeletonizer: ^1.1.1
  cached_network_image: ^3.3.1
  flutter_nested_categories:
    git:
      url: https://github.com/Iconica-Development/flutter_nested_categories
      ref: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
