name: flutter_shopping
description: "A new Flutter package project."
version: 3.0.0
homepage: https://github.com/Iconica-Development/flutter_shopping/packages/flutter_shopping
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  collection: ^1.18.0

  animated_toggle:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^0.0.3
  flutter_form_wizard:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^6.6.0

  shopping_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^3.0.0

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
  assets:
    - assets/
