name: flutter_order_details
description: "A Flutter module for order details."
version: 2.0.0
repository: https://github.com/Iconica-Development/flutter_shopping

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_toggle:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^0.0.3
  flutter_form_wizard:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^6.5.0
  flutter_shopping_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^2.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: 7.0.0
